﻿version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: staging
    networks:
      - starterBackend
    ports:
      - 80
    restart: on-failure
      
networks:
  starterBackend:
    name: starterBackend